In [1]:
# pandas用来处理表格型或异质型数据

In [2]:
import pandas as pd
import numpy as np

# 1.Series

In [3]:
#Seires是一种一维数据型对象，包含数据标签称为索引

In [4]:
obj = pd.Series([4,7,-5,3])

In [5]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [6]:
#索引从0到N-1（N为数据长度）

In [7]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [8]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
obj2 = pd.Series([4,7,-5,3],index=['d','b','a','c'])

In [10]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [11]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [12]:
obj2['a']

-5

In [13]:
obj2['d'] = 6

In [14]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [15]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [16]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [17]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [18]:
'b' in obj2

True

In [19]:
'e' in obj2

False

In [20]:
sdata = {'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}

In [21]:
obj3 = pd.Series(sdata)

In [22]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [23]:
states = ['California','Ohio','Oregon','Texas']

In [24]:
obj4 = pd.Series(sdata,index=states)

In [25]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [26]:
# isnull()缺失数据
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [27]:
# notnull()
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [28]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [29]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [30]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [31]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [32]:
# name属性
obj4.name = 'population'
obj4.index.name = 'state'

In [33]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [34]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [35]:
obj.index = ['Bob','Steve','Jeff','Ryan']

In [36]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

# 2.DataFrame表示矩阵数据表，它包含排序的列集合（二维）

In [37]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Navada'],
        'year':[2000,2001,2002,2001,2002,2003],
        'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame = pd.DataFrame(data)

In [38]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Navada  2003  3.2

In [39]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [40]:
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Navada  3.2

In [41]:
frame2 = pd.DataFrame(data,columns=['year','state','pop','debt'],
                     index=['one','two','three','four','five','six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Navada  3.2  NaN

In [42]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [43]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Navada
Name: state, dtype: object

In [44]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [45]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [46]:
frame2['debt'] = 16.5

In [47]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Navada  3.2  16.5

In [48]:
frame2['debt'] = np.arange(6.)

In [49]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Navada  3.2   5.0

In [50]:
# 值的长度必须与DataFrame长度相匹配

In [51]:
val = pd.Series([-1.2,-1.5,-1.7],index=['two','four','five'])

In [52]:
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [53]:
frame2['debt'] = val

In [54]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Navada  3.2   NaN

In [55]:
del frame2['debt']

In [56]:
frame2

year   state  pop
one    2000    Ohio  1.5
two    2001    Ohio  1.7
three  2002    Ohio  3.6
four   2001  Nevada  2.4
five   2002  Nevada  2.9
six    2003  Navada  3.2

In [57]:
frame2['debt'] = val

In [58]:
frame2['eastern'] = frame2.state == 'Ohio'

In [59]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Navada  3.2   NaN    False

In [60]:
del frame2['eastern']

In [61]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [62]:
pop = {'Nevada':{2001:2.4,2002:2.9},
       'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [63]:
#字典的键作为列，内部字典的键作为索引
frame3 = pd.DataFrame(pop)

In [64]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [65]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [66]:
pd.DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [67]:
#Seires的字典可以用于构造DataFrame
pdata = {'Ohio':frame3['Ohio'][:-1],
         'Nevada':frame3['Nevada'][:2]}

In [68]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [69]:
frame3.index.name = 'year';frame3.columns.name = 'state'

In [70]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [71]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [72]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Navada  3.2   NaN

In [73]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Navada', 3.2, nan]], dtype=object)

# 3.索引对象

In [74]:
obj = pd.Series(range(3),index=list('abc'))

In [75]:
index = obj.index

In [76]:
index

Index(['a', 'b', 'c'], dtype='object')

In [77]:
index[1:]

Index(['b', 'c'], dtype='object')

In [78]:
# 索引对象是不可变

In [79]:
labels = pd.Index(np.arange(3))

In [80]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [81]:
obj2 = pd.Series([1.5,-2.5,0],index=labels)

In [82]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [83]:
obj2.index is labels

True

In [84]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [85]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [86]:
'Ohio' in frame3.columns

True

In [87]:
2003 in frame3.index

False

In [88]:
dup_labels = pd.Index(['foo','foo','bar','bar'])

In [89]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

# 4.基本功能

In [90]:
# 重建索引

In [91]:
obj = pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])

In [92]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [93]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [94]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [95]:
obj3 = pd.Series(['blue','purple','yellow'],index=[0,2,4])

In [96]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [97]:
obj3.reindex(range(6),method='ffill')#fill向前填充，bfill向后填充

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [98]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                    index=['a','c','d'],
                    columns=['Ohio','Texas','California'])

In [99]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [100]:
frame2 = frame.reindex(['a','b','c','d'])

In [101]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [102]:
states = ['Texas','Utah','California']

In [103]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [104]:
frame.loc[['a','b','c','d'],states]

D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:1494: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [105]:
frame.reindex(['a','b','c','d'],fill_value=20)

Ohio  Texas  California
a     0      1           2
b    20     20          20
c     3      4           5
d     6      7           8

In [106]:
# 轴向上删除条目

In [107]:
obj = pd.Series(np.arange(5.),index=['a','b','c','d','e'])

In [108]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [109]:
#drop()
new_obj = obj.drop('c')

In [110]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [111]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [112]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index=['Ohio','Colorado','Utah','New York'],
                   columns=['one','two','three','four'])

In [113]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [114]:
data.drop(['Colorado','Ohio'])#axis=0默认

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [115]:
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [116]:
data.drop(['two','four'],axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [117]:
obj.drop('c',inplace=True)

In [118]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [119]:
# 5.2.3索引、选择与过滤

In [120]:
obj = pd.Series(np.arange(4.),index=['a','b','c','d'])

In [121]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [122]:
obj['b']

1.0

In [123]:
obj[1]

1.0

In [124]:
#序号索引

In [125]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [126]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [127]:
obj[[1,3]]#行序号,0开始

b    1.0
d    3.0
dtype: float64

In [128]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [129]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [130]:
obj['a':'c']#Series包含尾部

a    0.0
b    1.0
c    2.0
dtype: float64

In [131]:
obj['b':'c'] = 5

In [132]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [133]:
#DataFrame中索引

In [134]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index=['Ohio','Colorado','Utah','New York'],
                   columns=['one','two','three','four'])

In [135]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [136]:
# 列索引
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [137]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [138]:
# 行索引
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [139]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [140]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [141]:
data[data < 5] = 0

In [142]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [143]:
# 使用loc与iloc选择数据

In [144]:
#loc轴标签
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [145]:
# iloc整数标签
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [146]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [147]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [148]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [149]:
data.iloc[:,:3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [150]:
# 整数索引

In [151]:
ser = pd.Series(np.arange(3.))

In [152]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [153]:
# error ser[-1]

In [154]:
ser2 = pd.Series(np.arange(3.),index=['a','b','c'])

In [155]:
ser2[-1]

2.0

In [156]:
ser[:1]

0    0.0
dtype: float64

In [157]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [158]:
ser.iloc[:1]

0    0.0
dtype: float64

In [159]:
# 5.2.5算术和数据对齐

In [160]:
s1 = pd.Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])

In [161]:
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])

In [162]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [163]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [164]:
#没有交叠的标签位置，内部数据对齐会产生缺失值
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [165]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)),columns=list('bcd'),
                  index=['Ohio','Texas','Colorado'])

In [166]:
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),
                  index=['Utah','Ohio','Texas','Oregon'])

In [167]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [168]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [169]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [170]:
# 5.2.5.1使用填充值的算术方法

In [171]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),
                  columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),
                  columns=list('abcde'))

In [172]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [173]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [174]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [175]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [176]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [177]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [178]:
df1.reindex(columns=df2.columns,fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [179]:
df1.pow(2)

a     b      c      d
0   0.0   1.0    4.0    9.0
1  16.0  25.0   36.0   49.0
2  64.0  81.0  100.0  121.0

In [180]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [181]:
df1.rpow(2)

a      b       c       d
0    1.0    2.0     4.0     8.0
1   16.0   32.0    64.0   128.0
2  256.0  512.0  1024.0  2048.0

In [182]:
# 5.2.5.2 DataFrame和Series间的操作

In [183]:
arr = np.arange(12.).reshape((3,4))

In [184]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [185]:
arr[0]

array([0., 1., 2., 3.])

In [186]:
arr - arr[0] #广播机制

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [187]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                    columns=list('bde'),
                    index=['Utah','Ohio','Texas','Oregon'])

In [188]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [189]:
series = frame.iloc[0]

In [190]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [191]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [192]:
series2 = pd.Series(range(3),index=['b','e','f'])

In [193]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [194]:
series3 = frame['d']

In [195]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [196]:
frame.sub(series3,axis=0)#行上进行匹配

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

# 5.函数应用和映射

In [197]:
frame = pd.DataFrame(np.random.randn(4,3),columns=list('bde'),
                    index=['Utah','Ohio','Texas','Oregon'])

In [198]:
frame

b         d         e
Utah    0.045886 -1.282798 -0.392941
Ohio    0.469227 -0.431305 -1.736593
Texas   1.545081  0.529743  0.360874
Oregon  0.955921  0.187359  0.028426

In [199]:
np.abs(frame)

b         d         e
Utah    0.045886  1.282798  0.392941
Ohio    0.469227  0.431305  1.736593
Texas   1.545081  0.529743  0.360874
Oregon  0.955921  0.187359  0.028426

In [200]:
# apply

In [201]:
f = lambda x: x.max() - x.min()

In [202]:
frame.apply(f,axis=0)

b    1.499195
d    1.812541
e    2.097467
dtype: float64

In [203]:
frame.apply(f,axis=1)

Utah      1.328684
Ohio      2.205820
Texas     1.184206
Oregon    0.927495
dtype: float64

In [204]:
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])

In [205]:
frame.apply(f,axis=1)

min       max
Utah   -1.282798  0.045886
Ohio   -1.736593  0.469227
Texas   0.360874  1.545081
Oregon  0.028426  0.955921

In [206]:
frame.apply(f,axis=0)

b         d         e
min  0.045886 -1.282798 -1.736593
max  1.545081  0.529743  0.360874

In [207]:
#applymap

In [208]:
fmt = lambda x: '%.2f' % x

In [209]:
frame.applymap(fmt)

b      d      e
Utah    0.05  -1.28  -0.39
Ohio    0.47  -0.43  -1.74
Texas   1.55   0.53   0.36
Oregon  0.96   0.19   0.03

In [210]:
frame['e'].map(fmt)

Utah      -0.39
Ohio      -1.74
Texas      0.36
Oregon     0.03
Name: e, dtype: object

# 6.排序和排名

In [211]:
obj = pd.Series(range(4),index=['d','a','b','c'])

In [212]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [213]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [214]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                    index=['three','one'],
                    columns=['d','a','b','c'])

In [215]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [216]:
frame.sort_index(axis=0)

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [217]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [218]:
#ascending=False降序

In [219]:
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [220]:
obj = pd.Series([4,7,-3,2])

In [221]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [222]:
obj = pd.Series([4,np.nan,7,np.nan,-3,2])

In [223]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [224]:
frame = pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})

In [225]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [226]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [227]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [228]:
#rank

In [229]:
obj = pd.Series([7,-5,7,4,2,0,4])

In [230]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [231]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [232]:
obj.rank(ascending=False,method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [233]:
frame = pd.DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],
                      'c':[-2,5,8,-2.5]})

In [234]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [235]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [236]:
frame.rank(axis='index')

b    a    c
0  3.0  1.5  2.0
1  4.0  3.5  3.0
2  1.0  1.5  4.0
3  2.0  3.5  1.0

In [237]:
# 含有重复标签的轴索引

In [238]:
obj = pd.Series(range(5),index=list('aabbc'))

In [239]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [240]:
#is_unique检查是否唯一
obj.index.is_unique

False

In [241]:
obj['a']

a    0
a    1
dtype: int64

In [242]:
obj['c']

4

In [243]:
df = pd.DataFrame(np.random.randn(4,3),index=['a','a','b','b'])

In [244]:
df

0         1         2
a -0.460827  0.125511  0.257409
a  0.343532 -0.816588 -0.066000
b -1.558730 -0.323195  0.092856
b -1.071889  0.180467 -0.960755

In [245]:
df.loc['b']

0         1         2
b -1.558730 -0.323195  0.092856
b -1.071889  0.180467 -0.960755

# 7.描述性统计的概述与计算

In [246]:
df = pd.DataFrame([[1.4,np.nan],[7.1,-4.5],
                   [np.nan,np.nan],[0.75,-1.3]],
                  index=['a','b','c','d'],
                 columns=['one','two'])

In [247]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [248]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [249]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [250]:
#默认自动排除NA

In [251]:
df.mean(axis='columns',skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [252]:
df.idxmax()

one    b
two    d
dtype: object

In [253]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [254]:
obj = pd.Series(list('aabc')*4)

In [255]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [256]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [257]:
# 相关性和协方差

In [258]:
import pandas_datareader.data as web

In [259]:
all_data = {ticker:web.get_data_yahoo(ticker)
           for ticker in ['AAPL','IBM','MSFT','GOOG']}
price = pd.DataFrame({ticker:data['Adj Close']
                     for ticker,data in all_data.items()})
volume = pd.DataFrame({ticker:data['Volume']
                      for ticker,data in all_data.items()})

In [260]:
returns = price.pct_change()

In [261]:
returns = returns.dropna()

In [262]:
returns.head()

AAPL       IBM      MSFT      GOOG
Date                                              
2010-01-04  0.015565  0.011841  0.015420  0.010920
2010-01-05  0.001729 -0.012080  0.000323 -0.004404
2010-01-06 -0.015906 -0.006496 -0.006137 -0.025209
2010-01-07 -0.001848 -0.003462 -0.010400 -0.023280
2010-01-08  0.006648  0.010035  0.006897  0.013331

In [263]:
returns['MSFT'].corr(returns['IBM'])

0.4879343541388864

In [264]:
returns['MSFT'].cov(returns['IBM'])

8.689079843711344e-05

In [265]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.381363  0.453076  0.459101
IBM   0.381363  1.000000  0.487934  0.401581
MSFT  0.453076  0.487934  1.000000  0.535111
GOOG  0.459101  0.401581  0.535111  1.000000

In [266]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000266  0.000077  0.000107  0.000117
IBM   0.000077  0.000152  0.000087  0.000077
MSFT  0.000107  0.000087  0.000208  0.000120
GOOG  0.000117  0.000077  0.000120  0.000242

In [267]:
returns.corrwith(returns.IBM)

AAPL    0.381363
IBM     1.000000
MSFT    0.487934
GOOG    0.401581
dtype: float64

In [268]:
returns.corrwith(volume)

AAPL   -0.061654
IBM    -0.151889
MSFT   -0.090342
GOOG   -0.018808
dtype: float64

In [269]:
# 唯一值、计数、成员属性

In [270]:
obj = pd.Series(list('cadaabbcc'))

In [271]:
uniques = obj.unique()

In [272]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [273]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [274]:
pd.value_counts(obj.values,sort=False)

b    2
d    1
a    3
c    3
dtype: int64

In [275]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [276]:
mask = obj.isin(['b','c'])

In [277]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [278]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [279]:
to_match = pd.Series(['c','a','b','b','c','a'])

In [280]:
unique_vals = pd.Series(['c','b','a'])

In [281]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [282]:
data = pd.DataFrame({'Qu1':[1,3,4,3,4],
                     'Qu2':[2,3,1,2,3],
                     'Qu3':[1,5,2,4,4]})

In [283]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [284]:
result = data.apply(pd.value_counts,axis=1).fillna(0)

In [285]:
result

1    2    3    4    5
0  2.0  1.0  0.0  0.0  0.0
1  0.0  0.0  2.0  0.0  1.0
2  1.0  1.0  0.0  1.0  0.0
3  0.0  1.0  1.0  1.0  0.0
4  0.0  0.0  1.0  2.0  0.0